# Generated by Django 4.2.4 on 2023-08-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('deleted', models.BooleanField(default=False)),
                ('identity_number', models.CharField(help_text='Identity Number', max_length=128)),
                ('name', models.CharField(help_text='Name', max_length=128)),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
